### PR TITLE
K8s api

### PR DESCRIPTION
**Pull request by srueg**

### CODE REVIEW

**Comment by sebgoa** [comment]
why is the CA required ?

**Comment by srueg** [comment]
Because the route is of type `reencrypt` it needs to know and trust the destination CA (API server). https://docs.openshift.com/container-platform/3.11/architecture/networking/routes.html#secured-routes
Ingress objects don't validate the target CA, so it's not needed there. I'll change it to only be required if routes are enabled.

**Comment by srueg** [comment]
Ah, it already is only required if routes are enabled. If only ingress is used, there's no need for the CA.

**Comment by sebgoa** [comment]
perfect then

**Comment by srueg** [comment]
Gracias. Is the cloud build set up to automatically build the master branch?

**Comment by sebgoa** [comment]
yes....

**Pull request merged**
